TRAINER: viTrainer

DATASET:
  FEATURE_BATCH_SIZE: 60
  DICT_BATCH_SIZE: 60
  WORKERS: 2
  MIN_FREQ: 5
  SCENE_TEXT_THRESHOLD: 0.3
  VOCAB:
    TOKENIZER: null
    WORD_EMBEDDING: null
    WORD_EMBEDDING_CACHE: null
    BOS_TOKEN: <bos>
    EOS_TOKEN: <eos>
    PAD_TOKEN: <pad>
    UNK_TOKEN: <unk>
    USE_MAPPING: False
    PRETRAINED_LANGUAGE_MODEL: null
  JSON_PATH:
    TRAIN: features/OpenViIC/annotations/uit-openviic-train.json
    DEV: features/OpenViIC/annotations/uit-openviic-dev.json
    TEST: features/OpenViIC/annotations/uit-openviic-test.json
  FEATURE_PATH:
    FEATURES: features/OpenViIC/features/x152++_faster_rcnn
    SCENE_TEXT: null
    IMAGE: null

TRAINING:
  CHECKPOINT_PATH: saved_models
  LEARNING_RATE: 1.
  RL_LEARNING_RATE: 0.000005
  WARMUP: 10000
  SCORE: CIDEr
  GET_SCORES: True
  TRAINING_BEAM_SIZE: 5
  EVALUATING_BEAM_SIZE: 3
  PATIENCE: 5

MODEL:
  ARCHITECTURE: StandardTransformerUsingRegion
  NAME: transformer_region_x152_faster_rcnn
  DEVICE: cuda
  VISION_EMBEDDING:
    ARCHITECTURE: FeatureEmbedding
    D_FEATURE: 1024
    D_MODEL: 512
    DROPOUT: 0.1
  ENCODER:
    ARCHITECTURE: Encoder
    D_MODEL: 512
    LAYERS: 3
    SELF_ATTENTION:
      ARCHITECTURE: ScaledDotProductAttention
      HEAD: 8
      D_MODEL: 512
      D_KEY: 64
      D_VALUE: 64
      D_FF: 2048
      D_FEATURE: 2048
      MEMORY: 40
      USE_AOA: False
      CAN_BE_STATEFUL: False
      DROPOUT: .1
  DECODER:
    ARCHITECTURE: Decoder
    D_MODEL: 512
    LAYERS: 3
    ATTENTION:
      SELF_ATTENTION:
        ARCHITECTURE: ScaledDotProductAttention
        HEAD: 8
        D_MODEL: 512
        D_KEY: 64
        D_VALUE: 64
        D_FF: 2048
        D_FEATURE: 2048
        USE_AOA: False
        CAN_BE_STATEFUL: True
        DROPOUT: .1
      ENC_ATTENTION:
        ARCHITECTURE: ScaledDotProductAttention
        HEAD: 8
        D_MODEL: 512
        D_KEY: 64
        D_VALUE: 64
        D_FF: 2048
        D_FEATURE: 2048
        USE_AOA: False
        CAN_BE_STATEFUL: False
        DROPOUT: .1
    TEXT_EMBEDDING:
      ARCHITECTURE: UsualEmbedding
      D_MODEL: 512
      D_EMBEDDING: 300
      WORD_EMBEDDING: null
      WORD_EMBEDDING_CACHE: null
      DROPOUT: 0.1